spring:
  application:
    name: service-grade # es importante que este nombre sea unico dentro del ecosistema de microservicios en Eureka
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8085} # Importa la configuración desde el servidor de configuración
