spring:
  application:
    name: service-grade # es importante que este nombre sea unico dentro del ecosistema de microservicios en Eureka
  config:
    import: optional:configserver:http://localhost:8085