spring:
  application:
    name: server-api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: service-user 
              uri: lb://service-user 
              predicates: # Condiciones para enrutar solicitudes
                - Path=/api/v1/users/** 
                - Method=GET,POST,PUT,DELETE 
              filters:
                - AuthFilter # Filtro personalizado para autenticacion
            - id: service-grade
              uri: lb://service-grade
              predicates:
                - Path=/api/v1/grades/**
                - Method=GET,POST,PUT,DELETE
            - id: service-hotel
              uri: lb://service-hotel
              predicates:
                - Path=/api/v1/hotels/**, /api/v1/staffs/**
                - Method=GET,POST,PUT,DELETE
            - id: service-auth
              uri: lb://service-auth
              predicates:
                - Path=/api/v1/auth/**
                - Method=GET,POST,PUT,DELETE
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
        defaultZone: ${EUREKA_SERVER:http://localhost:9001}/eureka
server:
  port: 9002