spring:
  application:
    name: server-api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: service-user # Identificador �nico para la ruta
              uri: lb://service-user # URL del servicio de usuario registrado en Eureka (usando balanceo de carga)
              predicates: # Condiciones para enrutar solicitudes
                - Path=/api/v1/users/** # Patr�n de ruta para enrutar solicitudes
                - Method=GET,POST,PUT,DELETE # M�todos HTTP permitidos
            - id: service-grade
              uri: lb://service-grade
              predicates:
                - Path=/api/v1/grades/**
                - Method=GET,POST,PUT,DELETE
            - id: service-hotel
              uri: lb://service-hotel
              predicates:
                - Path=/api/v1/hotels/**, /api/v1/staffs/**
                - Method=GET,POST,PUT,DELETE
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
        defaultZone: http://localhost:8761/eureka # URL del servidor Eureka al que se conectar� el cliente
server:
  port: 8084