spring:
  application:
    name: service-hotel
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8085} # Importa la configuración desde el servidor de configuración
#  profiles:
#      active: prod