spring:
  application:
    name: service-user # Nombre unico del microservicio en Eureka
  config:
    import: configserver:http://localhost:8085 # Importa la configuración desde el servidor de configuración
#  profiles:
#    active: prod # Perfil activo para el entorno de desarrollo