## Config de servidor
spring:
  profiles:
    active: dev
  application:
    name: service-user # Nombre unico del microservicio en Eureka
  datasource:
    url: jdbc:mysql://localhost:3306/msvc_users
    username: root
    password: matichelo17
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  config:
    import: configserver:http://localhost:8085 # Importa la configuraci칩n desde el servidor de configuraci칩n
server:
  port: 8081
#eureka:
#  instance:
#    prefer-ip-address: true # Usa la direcci칩n IP en lugar del nombre del host
#  client:
#    fetch-registry: true # Permite que el servicio obtenga la lista de otros servicios registrados
#    register-with-eureka: true # Permite que el servicio se registre en Eureka
#    service-url:
#      defaultZone: http://localhost:8761/eureka # URL del servidor Eureka al que se conectar치 el cliente
#service:
#  grade:
#    name: service-grade
#  hotel:
#    name: service-hotel